info:
  app:
    name: sample-customer
    description: Customer Service

server:
  context-path: /${CONTEXT_PATH:customer}
  port: 8080

spring:
  application:
    name: sample-customer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
